version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ai_assistant_postgres
    environment:
      POSTGRES_DB: ai_assistant_marketplace
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai_assistant_backend
    ports:
      - "3001:3001"
    env_file:
      - ./env-example-backend.txt
    environment:
      - DATABASE_URL=postgresql://postgres:postgres123@postgres:5432/ai_assistant_marketplace?schema=public
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: sh -c "npm run prisma:generate && npm run prisma:push && npm run dev"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ai_assistant_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev

volumes:
  postgres_data:
